version: '3.8'

volumes:
  vuln-sprint-mariadb-data:
    null
services:
  app:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick an version of Java: 11, 17.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 11-bullseye
        # Options
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: ""
        INSTALL_GRADLE: "false"
        GRADLE_VERSION: ""
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: mariadb
    build: ../db
    # ports:
      # - 3306:3306
    restart: unless-stopped
    volumes:
      - vuln-sprint-mariadb-data:/var/lib/mysql
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      MYSQL_ROOT_PASSWORD: "Password"
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
